// <auto-generated />
using System;
using DashyDashboard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashyDashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601143027_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.AttestationLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("AssociateId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<int>("CycleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ToolCount")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("CycleID");

                    b.ToTable("AttestationLogs", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.Client", b =>
                {
                    b.Property<string>("ClientID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClientDesc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Tier")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ClientID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.ClientTool", b =>
                {
                    b.Property<int>("ToolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToolID"));

                    b.Property<string>("ClientID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Application Name");

                    b.HasKey("ToolID");

                    b.ToTable("ClientTools", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.Cycle", b =>
                {
                    b.Property<int>("CycleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CycleID"));

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("CycleID");

                    b.ToTable("Cycles", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.IFHGFHMapping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GFH")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IFH")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID");

                    b.ToTable("IFHGFHMapping", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.LoginLog", b =>
                {
                    b.Property<int>("LoginLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginLogID"));

                    b.Property<string>("AssociateId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoginLogID");

                    b.ToTable("LoginLogs", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.SuperUser", b =>
                {
                    b.Property<int>("SuperUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperUserID"));

                    b.Property<string>("AccessLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AssociateId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("TRUE");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SuperUserID");

                    b.HasIndex("AssociateId", "RoleName", "Department")
                        .IsUnique();

                    b.ToTable("SuperUsers", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.ToolCycleAttestation", b =>
                {
                    b.Property<int>("CycleID")
                        .HasColumnType("int");

                    b.Property<string>("AssociateId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<string>("ClientID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ToolID")
                        .HasColumnType("int");

                    b.Property<string>("AttestationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("UsedThisCycle")
                        .HasColumnType("bit");

                    b.HasKey("CycleID", "AssociateId", "ClientID", "ToolID");

                    b.HasIndex("AssociateId");

                    b.ToTable("ToolCycleAttestation", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.User", b =>
                {
                    b.Property<string>("AssociateId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<string>("Department")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmailAddr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMailAddr");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PrimaryLocationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssociateId");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.UserToolAccess", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Access")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Application Name");

                    b.Property<string>("AssociateId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<string>("ClientID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("ClientToolToolID")
                        .HasColumnType("int");

                    b.Property<string>("FromDate")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FromDate");

                    b.Property<string>("ToDate")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ToDate");

                    b.Property<string>("UserAssociateId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("AssociateId");

                    b.HasIndex("ClientToolToolID");

                    b.HasIndex("UserAssociateId");

                    b.HasIndex("ClientID", "ApplicationName");

                    b.ToTable("UsersToolAccess", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.AttestationLog", b =>
                {
                    b.HasOne("DashyDashboard.Api.Models.Domain.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.ClientTool", b =>
                {
                    b.HasOne("DashyDashboard.Api.Models.Domain.Client", "Client")
                        .WithMany("Tools")
                        .HasForeignKey("ClientID");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.ToolCycleAttestation", b =>
                {
                    b.HasOne("DashyDashboard.Api.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("AssociateId");

                    b.HasOne("DashyDashboard.Api.Models.Domain.Cycle", "Cycle")
                        .WithMany("Attestations")
                        .HasForeignKey("CycleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.User", b =>
                {
                    b.HasOne("DashyDashboard.Api.Models.Domain.User", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.UserToolAccess", b =>
                {
                    b.HasOne("DashyDashboard.Api.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("AssociateId");

                    b.HasOne("DashyDashboard.Api.Models.Domain.ClientTool", null)
                        .WithMany("UserAccess")
                        .HasForeignKey("ClientToolToolID");

                    b.HasOne("DashyDashboard.Api.Models.Domain.User", null)
                        .WithMany("ToolAccess")
                        .HasForeignKey("UserAssociateId");

                    b.HasOne("DashyDashboard.Api.Models.Domain.ClientTool", "ClientTool")
                        .WithMany()
                        .HasForeignKey("ClientID", "ApplicationName")
                        .HasPrincipalKey("ClientID", "ToolName");

                    b.Navigation("ClientTool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.Client", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.ClientTool", b =>
                {
                    b.Navigation("UserAccess");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.Cycle", b =>
                {
                    b.Navigation("Attestations");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.User", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("ToolAccess");
                });
#pragma warning restore 612, 618
        }
    }
}
